import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

type DayInput = { title: string; body: string };

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    lineHeight: 1.5,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#dddddd",
  },
  brand: {
    fontSize: 9,
    letterSpacing: 2,
    color: "#888888",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  prompt: {
    fontSize: 11,
    color: "#555555",
    fontStyle: "italic",
  },
  dayBlock: {
    marginBottom: 18,
    paddingTop: 4,
  },
  dayTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    color: "#0a0a0a",
  },
  dayChip: {
    fontSize: 8,
    color: "#888888",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  body: {
    color: "#333333",
    fontSize: 11,
    lineHeight: 1.6,
  },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#aaaaaa",
    textAlign: "center",
  },
});

function parseDays(text: string): {
  preamble: string;
  days: DayInput[];
  postamble: string;
} {
  const lines = text.split("\n");
  const days: DayInput[] = [];
  let preamble: string[] = [];
  let postamble: string[] = [];
  let current: DayInput | null = null;
  let seenAnyDay = false;

  for (const line of lines) {
    const dayMatch = line.match(/^##\s+(.*)$/);
    if (dayMatch) {
      if (current) days.push(current);
      current = { title: dayMatch[1].trim(), body: "" };
      seenAnyDay = true;
      continue;
    }
    if (current) {
      current.body += (current.body ? "\n" : "") + line;
    } else if (!seenAnyDay) {
      preamble.push(line);
    } else {
      postamble.push(line);
    }
  }
  if (current) days.push(current);

  return {
    preamble: preamble.join("\n").trim(),
    days: days.map((d) => ({ ...d, body: stripMarkdown(d.body.trim()) })),
    postamble: stripMarkdown(postamble.join("\n").trim()),
  };
}

// Strip the markdown we care about: **bold**, _italic_, list markers
function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/^[-*]\s+/gm, "• ")
    .trim();
}

export function ItineraryPDF({
  prompt,
  itineraryText,
  savedAt,
}: {
  prompt: string;
  itineraryText: string;
  savedAt: string;
}) {
  const { preamble, days, postamble } = parseDays(itineraryText);
  const fmtDate = new Date(savedAt).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Wanderloop · {fmtDate}</Text>
          <Text style={styles.title}>Your trip</Text>
          <Text style={styles.prompt}>"{prompt}"</Text>
        </View>

        {preamble && (
          <View style={styles.dayBlock}>
            <Text style={styles.body}>{preamble}</Text>
          </View>
        )}

        {days.map((d, i) => (
          <View key={i} style={styles.dayBlock} wrap={false}>
            <Text style={styles.dayChip}>Day {i + 1}</Text>
            <Text style={styles.dayTitle}>
              {d.title.replace(/^Day\s*\d+\s*[—\-:]\s*/i, "")}
            </Text>
            <Text style={styles.body}>{d.body}</Text>
          </View>
        ))}

        {postamble && (
          <View style={styles.dayBlock}>
            <Text style={styles.body}>{postamble}</Text>
          </View>
        )}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages} · generated by wanderloop.vercel.app`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
